version: "3.9"

services:
  # Laravel PHP-FPM
  laravel:
    build:
      context: ./backend
    container_name: laravel
    volumes:
      - ./backend:/var/www/html
    networks:
      - found_lost_net
    command: >
      sh -c "php artisan config:clear && 
             php artisan cache:clear && 
             php-fpm"

  # Nginx for Laravel
  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    depends_on:
      - laravel
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - found_lost_net
    ports:
      - "8000:80" # You will access backend via http://localhost:8000

  # React Vite dev server
  react:
    image: node:22-alpine
    container_name: react
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173" # You will access frontend via http://localhost:5173
    networks:
      - found_lost_net

  # MySQL database
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: Test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql # Changed to separate volume
    command: --skip-name-resolve
    networks:
      - found_lost_net

networks:
  found_lost_net:
   driver: bridge



volumes:
  mysql_data:
